version: '3.8'

services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.9.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka-server:
    container_name: kafka-server
    image: confluentinc/cp-kafka:7.9.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-server:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: "echo 'exit' | nc localhost 9092"
      interval: 10s
      retries: 5
      timeout: 5s

  events_storage:
    container_name: events_storage
    environment:
      POSTGRES_DB: events_storage
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "events_storage"]
      interval: 10s
      retries: 5
      timeout: 5s
    image: postgres:13
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./streaming_ingestion/infrastructure/events_storage.sql:/docker-entrypoint-initdb.d/01_init.sql

  events_generator:
    build:
      context: events_generator/.
      dockerfile: Dockerfile.Python
    container_name: events_generator
    depends_on:
      kafka-server:
        condition: service_healthy
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "grep -q 'Writing event' /app/logs/events_generator.log"]
      interval: 10s
      retries: 5
      timeout: 5s

  streaming_ingestion:
    build:
      context: streaming_ingestion/.
      dockerfile: Dockerfile.StreamingIngestion
    container_name: streaming_ingestion
    depends_on:
      kafka-server:
        condition: service_healthy
      events_storage:
        condition: service_healthy
      events_generator:
        condition: service_healthy
    ports:
      - "4040:4040"
