version: '3.8'

services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.9.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - gateway

  kafka-server:
    container_name: kafka-server
    image: confluentinc/cp-kafka:7.9.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-server:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: "echo 'exit' | nc localhost 9092"
      interval: 10s
      retries: 5
      timeout: 5s
    networks:
      - gateway

  events_storage:
    container_name: events_storage
    environment:
      POSTGRES_DB: events_storage
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "events_storage"]
      interval: 10s
      retries: 5
      timeout: 5s
    image: postgres:13
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./streaming_ingestion/infrastructure/events_storage.sql:/docker-entrypoint-initdb.d/01_init.sql
    networks:
      - gateway

  nginx:
    image: nginx:alpine
    container_name: nginx-gateway
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/html:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    depends_on:
      storage_admin:
        condition: service_started
      metabase:
        condition: service_started
      streaming_ingestion:
        condition: service_started
    networks:
      - gateway


  storage_admin:
    container_name: storage_admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "root@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "1234"
    ports:
      - "16543:80"
    depends_on:
      events_storage:
        condition: service_healthy
    networks:
      - gateway

  metabase:
    container_name: metabase
    image: metabase/metabase
    ports:
      - "3000:3000"
    networks:
      - gateway

  events_generator:
    build:
      context: events_generator/.
      dockerfile: Dockerfile.Python
    container_name: events_generator
    depends_on:
      kafka-server:
        condition: service_healthy
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "grep -q 'Writing event' /app/logs/events_generator.log"]
      interval: 10s
      retries: 5
      timeout: 5s
    networks:
      - gateway

  streaming_ingestion:
    build:
      context: streaming_ingestion/.
      dockerfile: Dockerfile.StreamingIngestion
    container_name: streaming_ingestion
    depends_on:
      kafka-server:
        condition: service_healthy
      events_storage:
        condition: service_healthy
      events_generator:
        condition: service_healthy
    ports:
      - "4040:4040"
    networks:
    - gateway

networks:
  gateway:
    driver: bridge
