FROM apache/spark-py:v3.4.0

COPY ingestion.py /app/ingestion.py

# add spark-submit path
ENV PATH="$PATH:/opt/spark/bin"

# to ivy2 directory access
USER root

# getting postgresql connector
RUN wget https://jdbc.postgresql.org/download/postgresql-42.6.0.jar -O /opt/spark/jars/postgresql-42.6.0.jar

# expose Spark UI port
EXPOSE 4040

# installing kafka and connector dependencies
CMD ["spark-submit", \
    "--conf", "spark.ui.host=0.0.0.0", \
    "--jars", "/opt/spark/jars/postgresql-42.6.0.jar", \
    "--packages", "org.apache.spark:spark-sql-kafka-0-10_2.12:3.4.0", \
    "/app/ingestion.py"]